import type { Ship, Upgrade, Ability, ShipDealer, LevelProgression, CareerProgression, CareerType } from "./types"

// Level progression system
export const LEVEL_PROGRESSION: LevelProgression[] = [
  { level: 1, xpRequired: 0, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 5 },
  { level: 2, xpRequired: 100, abilitySlots: 1, bonusUpgradeSlots: ["weapon"], threatValue: 10 },
  { level: 3, xpRequired: 250, abilitySlots: 2, bonusUpgradeSlots: ["weapon"], threatValue: 15 },
  { level: 4, xpRequired: 450, abilitySlots: 2, bonusUpgradeSlots: ["weapon", "system"], threatValue: 20 },
  { level: 5, xpRequired: 700, abilitySlots: 3, bonusUpgradeSlots: ["weapon", "system"], threatValue: 25 },
  { level: 6, xpRequired: 1000, abilitySlots: 3, bonusUpgradeSlots: ["weapon", "system", "shield"], threatValue: 30 },
  { level: 7, xpRequired: 1350, abilitySlots: 4, bonusUpgradeSlots: ["weapon", "system", "shield"], threatValue: 35 },
  {
    level: 8,
    xpRequired: 1750,
    abilitySlots: 4,
    bonusUpgradeSlots: ["weapon", "weapon", "system", "shield"],
    threatValue: 40,
  },
]

// Ships database
export const SHIPS: Ship[] = [
  {
    id: "xwing",
    name: "X-wing Starfighter",
    manufacturer: "Incom Corporation",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "torpedo", filled: false },
      { type: "astromech", filled: false },
      { type: "modification", filled: false },
      { type: "configuration", filled: false },
    ],
    threatValue: 50,
    cost: 1000,
    description: "Versatile multi-role fighter with excellent balance",
  },
  {
    id: "ywing",
    name: "Y-wing Bomber",
    manufacturer: "Koensayr Manufacturing",
    baseSlots: [
      { type: "turret", filled: false },
      { type: "torpedo", filled: false },
      { type: "missile", filled: false },
      { type: "astromech", filled: false },
      { type: "gunner", filled: false },
    ],
    threatValue: 60,
    cost: 1200,
    description: "Heavy bomber with extra weapon hardpoints",
  },
  {
    id: "awing",
    name: "A-wing Interceptor",
    manufacturer: "Alliance Underground Engineering",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "modification", filled: false },
      { type: "modification", filled: false },
      { type: "tech", filled: false },
    ],
    threatValue: 45,
    cost: 900,
    description: "Lightning-fast interceptor with superior maneuverability",
  },
  {
    id: "tiefighter",
    name: "TIE Fighter",
    manufacturer: "Sienar Fleet Systems",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "modification", filled: false },
      { type: "configuration", filled: false },
    ],
    threatValue: 35,
    cost: 700,
    description: "Imperial standard fighter, cheap and deadly in numbers",
  },
  {
    id: "tieinterceptor",
    name: "TIE Interceptor",
    manufacturer: "Sienar Fleet Systems",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "cannon", filled: false },
      { type: "missile", filled: false },
      { type: "modification", filled: false },
      { type: "tech", filled: false },
    ],
    threatValue: 55,
    cost: 1100,
    description: "Advanced TIE variant with enhanced firepower",
  },
  {
    id: "tiebomber",
    name: "TIE Bomber",
    manufacturer: "Sienar Fleet Systems",
    baseSlots: [
      { type: "torpedo", filled: false },
      { type: "missile", filled: false },
      { type: "payload", filled: false },
      { type: "payload", filled: false },
      { type: "gunner", filled: false },
    ],
    threatValue: 65,
    cost: 1300,
    description: "Heavy ordnance platform for bombing runs",
  },
  {
    id: "bwing",
    name: "B-wing Heavy Assault Fighter",
    manufacturer: "Slayn & Korpil",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "torpedo", filled: false },
      { type: "missile", filled: false },
      { type: "modification", filled: false },
      { type: "modification", filled: false },
      { type: "tech", filled: false },
    ],
    threatValue: 75,
    cost: 1500,
    description: "Heavily armed and shielded assault fighter",
  },
  {
    id: "zcargo",
    name: "Z-95 Headhunter",
    manufacturer: "Incom/Subpro",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 30,
    cost: 600,
    description: "Reliable older model, perfect for beginners",
  },
  {
    id: "vwing",
    name: "V-wing Airspeeder",
    manufacturer: "Kuat Systems Engineering",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "modification", filled: false },
      { type: "sensor", filled: false },
      { type: "crew", filled: false },
    ],
    threatValue: 40,
    cost: 800,
    description: "Atmospheric fighter adapted for space combat",
  },
  {
    id: "salvage1",
    name: "Salvaged Z-95 Frame",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 20,
    cost: 0, // Junkyard salvage ships are free
    description: "Barely functional fighter frame salvaged from a scrapyard",
  },
  {
    id: "salvage2",
    name: "Refurbished Cargo Hauler",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "illicit", filled: false },
      { type: "illicit", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 25,
    cost: 0, // Junkyard salvage ships are free
    description: "Old cargo ship with patched hull plating",
  },
  {
    id: "salvage3",
    name: "Modified Patrol Craft",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "sensor", filled: false },
      { type: "tech", filled: false },
    ],
    threatValue: 30,
    cost: 0, // Junkyard salvage ships are free
    description: "Former patrol vessel with questionable modifications",
  },
  {
    id: "salvage4",
    name: "Experimental Prototype",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "missile", filled: false },
      { type: "modification", filled: false },
      { type: "tech", filled: false },
    ],
    threatValue: 40,
    cost: 0, // Junkyard salvage ships are free
    description: "Abandoned prototype with unusual design features",
  },
]

// Upgrades database
export const UPGRADES: Upgrade[] = [
  // Cannons
  {
    id: "laser1",
    name: "Standard Laser Cannon",
    type: "cannon",
    slotsRequired: 1,
    threatValue: 5,
    cost: 100,
    description: "Basic energy weapon",
  },
  {
    id: "laser2",
    name: "Heavy Laser Cannon",
    type: "cannon",
    slotsRequired: 1,
    threatValue: 10,
    cost: 250,
    description: "Increased damage output",
  },
  {
    id: "ion",
    name: "Ion Cannon",
    type: "cannon",
    slotsRequired: 1,
    threatValue: 8,
    cost: 200,
    description: "Disables enemy systems",
  },

  // Torpedoes
  {
    id: "proton",
    name: "Proton Torpedoes",
    type: "torpedo",
    slotsRequired: 1,
    threatValue: 20,
    cost: 500,
    description: "High-yield explosive ordnance",
  },
  {
    id: "adv_proton",
    name: "Advanced Proton Torpedoes",
    type: "torpedo",
    slotsRequired: 1,
    threatValue: 25,
    cost: 650,
    description: "Enhanced targeting and payload",
  },

  // Missiles
  {
    id: "concussion",
    name: "Concussion Missiles",
    type: "missile",
    slotsRequired: 1,
    threatValue: 18,
    cost: 450,
    description: "Area effect missiles",
  },
  {
    id: "homing",
    name: "Homing Missiles",
    type: "missile",
    slotsRequired: 1,
    threatValue: 15,
    cost: 400,
    description: "Lock-on tracking missiles",
  },

  // Turrets
  {
    id: "turbo",
    name: "Turbolaser Battery",
    type: "turret",
    slotsRequired: 1,
    threatValue: 35,
    cost: 800,
    description: "Capital ship grade weapon",
  },
  {
    id: "ion_turret",
    name: "Ion Cannon Turret",
    type: "turret",
    slotsRequired: 1,
    threatValue: 22,
    cost: 550,
    description: "360-degree ion coverage",
  },

  // Modifications
  {
    id: "shield1",
    name: "Shield Upgrade",
    type: "modification",
    slotsRequired: 1,
    threatValue: 5,
    cost: 150,
    description: "Enhanced deflector shields",
  },
  {
    id: "shield2",
    name: "Advanced Shields",
    type: "modification",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Military-grade shielding",
  },
  {
    id: "engine1",
    name: "Engine Upgrade",
    type: "modification",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Improved thrust and speed",
  },
  {
    id: "hull",
    name: "Hull Upgrade",
    type: "modification",
    slotsRequired: 1,
    threatValue: 6,
    cost: 200,
    description: "Reinforced hull plating",
  },

  // Tech
  {
    id: "sensor1",
    name: "Advanced Sensors",
    type: "tech",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Long range detection",
  },
  {
    id: "sensor2",
    name: "Tactical Scanner",
    type: "tech",
    slotsRequired: 1,
    threatValue: 18,
    cost: 550,
    description: "Full battlefield awareness",
  },
  {
    id: "system1",
    name: "Electronic Countermeasures",
    type: "tech",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Jamming equipment",
  },
  {
    id: "system2",
    name: "Cloaking Device",
    type: "tech",
    slotsRequired: 2,
    threatValue: 25,
    cost: 700,
    description: "Temporary invisibility",
  },

  // Crew
  {
    id: "crew1",
    name: "Co-pilot",
    type: "crew",
    slotsRequired: 1,
    threatValue: 5,
    cost: 200,
    description: "Additional crew member",
  },
  {
    id: "crew3",
    name: "Navigator",
    type: "crew",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Expert navigation assistance",
  },

  // Gunner
  {
    id: "crew2",
    name: "Expert Gunner",
    type: "gunner",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Dedicated weapons specialist",
  },
  {
    id: "gunner2",
    name: "Veteran Tail Gunner",
    type: "gunner",
    slotsRequired: 1,
    threatValue: 12,
    cost: 350,
    description: "Experienced rear defense",
  },

  // Astromech
  {
    id: "r2d2",
    name: "R2 Astromech",
    type: "astromech",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Repair and navigation droid",
  },
  {
    id: "r5",
    name: "R5 Astromech",
    type: "astromech",
    slotsRequired: 1,
    threatValue: 6,
    cost: 200,
    description: "Basic repair droid",
  },

  // Illicit
  {
    id: "cargo1",
    name: "Contraband Cybernetics",
    type: "illicit",
    slotsRequired: 1,
    threatValue: 5,
    cost: 200,
    description: "Black market enhancements",
  },
  {
    id: "cargo2",
    name: "Smuggling Compartment",
    type: "illicit",
    slotsRequired: 1,
    threatValue: 3,
    cost: 150,
    description: "Hidden cargo space",
  },

  // Payload
  {
    id: "payload1",
    name: "Seismic Charges",
    type: "payload",
    slotsRequired: 1,
    threatValue: 20,
    cost: 500,
    description: "Devastating area bombs",
  },
  {
    id: "payload2",
    name: "Proximity Mines",
    type: "payload",
    slotsRequired: 1,
    threatValue: 15,
    cost: 400,
    description: "Deployable mine field",
  },

  // Sensor
  {
    id: "sensor3",
    name: "Targeting Computer",
    type: "sensor",
    slotsRequired: 1,
    threatValue: 5,
    cost: 150,
    description: "Improved weapon accuracy",
  },
  {
    id: "sensor4",
    name: "Fire Control System",
    type: "sensor",
    slotsRequired: 1,
    threatValue: 12,
    cost: 350,
    description: "Advanced targeting suite",
  },

  // Configuration
  {
    id: "config1",
    name: "Stabilized S-Foils",
    type: "configuration",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Improved wing configuration",
  },
  {
    id: "config2",
    name: "Pivot Wing",
    type: "configuration",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Adaptive wing system",
  },

  // Title
  {
    id: "title1",
    name: "Red Squadron",
    type: "title",
    slotsRequired: 1,
    threatValue: 15,
    cost: 400,
    description: "Elite squadron designation",
  },
  {
    id: "title2",
    name: "Rogue Squadron",
    type: "title",
    slotsRequired: 1,
    threatValue: 20,
    cost: 500,
    description: "Legendary squadron status",
  },
]

// Abilities database
export const ABILITIES: Ability[] = [
  {
    id: "ace1",
    name: "Ace Pilot",
    xpCost: 50,
    threatValue: 10,
    description: "Improved maneuverability in combat",
    requiredLevel: 1,
    careers: ["Professional", "Gambler", "Miner"],
  },
  {
    id: "marks1",
    name: "Marksman",
    xpCost: 50,
    threatValue: 10,
    description: "Increased weapon accuracy",
    requiredLevel: 1,
    careers: ["Professional", "Demolitions", "Cyborg"],
  },
  {
    id: "tough1",
    name: "Tough",
    xpCost: 50,
    threatValue: 8,
    description: "Increased hull integrity",
    requiredLevel: 1,
    careers: ["Gearhead", "Cyborg", "Miner"],
  },
  {
    id: "leader1",
    name: "Squad Leader",
    xpCost: 100,
    threatValue: 15,
    description: "Bonus to nearby allies",
    requiredLevel: 2,
    careers: ["Organizer", "Professional"],
  },
  {
    id: "sniper",
    name: "Sniper",
    xpCost: 100,
    threatValue: 15,
    description: "Long range attack bonus",
    requiredLevel: 2,
    careers: ["Professional", "Demolitions"],
  },
  {
    id: "evasive",
    name: "Evasive Maneuvers",
    xpCost: 150,
    threatValue: 20,
    description: "Harder to hit in combat",
    requiredLevel: 3,
    careers: ["Gambler", "Slicer", "Miner"],
  },
  {
    id: "rapid",
    name: "Rapid Fire",
    xpCost: 150,
    threatValue: 20,
    description: "Fire weapons faster",
    requiredLevel: 3,
    careers: ["Gambler", "Demolitions", "Cyborg"],
  },
  {
    id: "shield_expert",
    name: "Shield Expert",
    xpCost: 200,
    threatValue: 18,
    description: "Shields recharge faster",
    requiredLevel: 4,
    careers: ["Slicer", "Gearhead", "Cyborg"],
  },
  {
    id: "veteran",
    name: "Veteran",
    xpCost: 200,
    threatValue: 25,
    description: "Bonus to all combat rolls",
    requiredLevel: 5,
    careers: ["Organizer", "Professional", "Miner"],
  },
  {
    id: "legendary",
    name: "Legendary Pilot",
    xpCost: 300,
    threatValue: 35,
    description: "Master of space combat",
    requiredLevel: 7,
    careers: ["Professional", "Gambler", "Cyborg"],
  },
]

// Ship dealers
export const SHIP_DEALERS: ShipDealer[] = [
  {
    id: "rebel",
    name: "Rebel Alliance Quartermaster",
    description: "Specializes in Rebel Alliance fighters and bombers",
    shipIds: ["xwing", "ywing", "awing", "bwing", "zcargo"],
  },
  {
    id: "imperial",
    name: "Imperial Surplus Depot",
    description: "Sells captured and surplus Imperial vessels",
    shipIds: ["tiefighter", "tieinterceptor", "tiebomber"],
  },
  {
    id: "independent",
    name: "Independent Trader",
    description: "Variety of ships from various manufacturers",
    shipIds: ["zcargo", "vwing", "xwing", "tiefighter"],
  },
  {
    id: "junkyard",
    name: "Junkyard",
    description: "Roll the dice for a random salvage ship - you never know what you'll get!",
    shipIds: ["salvage1", "salvage2", "salvage3", "salvage4"],
  },
]

// Placeholder slot data - will be updated when user provides specific slot configurations
export const CAREER_PROGRESSIONS: CareerProgression[] = [
  {
    career: "Organizer",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["crew"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["crew"], threatValue: 6, initiative: 3 },
      { level: 4, xpRequired: 16, abilitySlots: 2, bonusUpgradeSlots: ["crew", "tech"], threatValue: 8, initiative: 3 },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["crew", "tech"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["crew", "tech", "illicit"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["crew", "tech", "illicit"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["crew", "crew", "tech", "illicit"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
  {
    career: "Professional",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 3 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["sensor"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["sensor"], threatValue: 6, initiative: 4 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["sensor", "tech"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["sensor", "tech"],
        threatValue: 10,
        initiative: 5,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["sensor", "tech", "crew"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["sensor", "tech", "crew"],
        threatValue: 14,
        initiative: 6,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["sensor", "sensor", "tech", "crew"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Gambler",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["illicit"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["illicit"], threatValue: 6, initiative: 3 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["illicit", "crew"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "crew"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "crew", "tech"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "crew", "tech"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "illicit", "crew", "tech"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Slicer",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 3 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["tech"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["tech"], threatValue: 6, initiative: 4 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["tech", "sensor"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["tech", "sensor"],
        threatValue: 10,
        initiative: 5,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["tech", "sensor", "tech"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["tech", "sensor", "tech"],
        threatValue: 14,
        initiative: 6,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["tech", "tech", "sensor", "sensor"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Gearhead",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["modification"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["modification"], threatValue: 6, initiative: 3 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 8,
        initiative: 3,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech", "modification"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "tech", "modification"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "modification", "tech", "tech"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
  {
    career: "Demolitions",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["missile"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["missile"], threatValue: 6, initiative: 3 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["missile", "torpedo"],
        threatValue: 8,
        initiative: 3,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["missile", "torpedo"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["missile", "torpedo", "payload"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["missile", "torpedo", "payload"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["missile", "torpedo", "payload", "cannon"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
  {
    career: "Cyborg",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 3 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["modification"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["modification"], threatValue: 6, initiative: 4 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 10,
        initiative: 5,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech", "cannon"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "tech", "cannon"],
        threatValue: 14,
        initiative: 6,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "modification", "tech", "cannon"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Miner",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 1 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["illicit"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["illicit"], threatValue: 6, initiative: 2 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["illicit", "modification"],
        threatValue: 8,
        initiative: 3,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "modification"],
        threatValue: 10,
        initiative: 3,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "modification", "crew"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "modification", "crew"],
        threatValue: 14,
        initiative: 4,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "illicit", "modification", "crew"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
]

// Helper function to get career progression
export function getCareerProgression(career: CareerType): LevelProgression[] {
  const careerData = CAREER_PROGRESSIONS.find((cp) => cp.career === career)
  return careerData?.levels || CAREER_PROGRESSIONS[0].levels
}
