import type { Ship, Upgrade, Ability, ShipDealer, LevelProgression, CareerProgression, CareerType } from "./types"

// Level progression system
export const LEVEL_PROGRESSION: LevelProgression[] = [
  { level: 1, xpRequired: 0, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 5 },
  { level: 2, xpRequired: 100, abilitySlots: 1, bonusUpgradeSlots: ["weapon"], threatValue: 10 },
  { level: 3, xpRequired: 250, abilitySlots: 2, bonusUpgradeSlots: ["weapon"], threatValue: 15 },
  { level: 4, xpRequired: 450, abilitySlots: 2, bonusUpgradeSlots: ["weapon", "system"], threatValue: 20 },
  { level: 5, xpRequired: 700, abilitySlots: 3, bonusUpgradeSlots: ["weapon", "system"], threatValue: 25 },
  { level: 6, xpRequired: 1000, abilitySlots: 3, bonusUpgradeSlots: ["weapon", "system", "shield"], threatValue: 30 },
  { level: 7, xpRequired: 1350, abilitySlots: 4, bonusUpgradeSlots: ["weapon", "system", "shield"], threatValue: 35 },
  {
    level: 8,
    xpRequired: 1750,
    abilitySlots: 4,
    bonusUpgradeSlots: ["weapon", "weapon", "system", "shield"],
    threatValue: 40,
  },
]

// Ships database
export const SHIPS: Ship[] = [
  {
    id: "tyewing",
    name: "TYE-Wing",
    manufacturer: "Made It Myself",
    baseSlots: [
      { type: "illicit", filled: false },
    ],
    threatValue: 10,
    cost: 7000,
    description: "The easiest to build of the Patchwork ships.",
  },
  {
    id: "tnt",
    name: "Totally Normal TIE",
    manufacturer: "Made It Myself",
    baseSlots: [
      { type: "illicit", filled: false },
    ],
    threatValue: 10,
    cost: 0,
    description: "There has got to be a weapon system that can be mounted on this somewhere in the junkyard",
  },
  {
    id: "ytie",
    name: "Y-TIE",
    manufacturer: "Made It Myself",
    baseSlots: [
      { type: "illicit", filled: false },
      { type: "astromech", filled: false },
      { type: "modification", filled: false },
      { type: "turret", filled: false },
    ],
    threatValue: 15,
    cost: 11000,
    description: "A little sturdy but slow and low firepower.",
  },
  {
    id: "xwing",
    name: "T-65 X-wing",
    manufacturer: "Incom Corporation",
    baseSlots: [
      { type: "illicit", filled: false },
      { type: "torpedo", filled: false },
      { type: "astromech", filled: false },
      { type: "modification", filled: false },
      { type: "configuration", filled: false },
    ],
    threatValue: 40,
    cost: 82000,
    description: "Versatile multi-role fighter with excellent balance",
  },
  {
    id: "ywing",
    name: "BTL-A4 Y-wing",
    manufacturer: "Koensayr Manufacturing",
    baseSlots: [
      { type: "turret", filled: false },
      { type: "torpedo", filled: false },
      { type: "missile", filled: false },
      { type: "payload", filled: false },
      { type: "astromech", filled: false },
      { type: "gunner", filled: false },
      { type: "illicit", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 32,
    cost: 32000,
    description: "Heavy bomber with extra weapon hardpoints",
  },
  {
    id: "awing",
    name: "RZ-1 A-wing",
    manufacturer: "Alliance Underground Engineering",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 30,
    cost: 62000,
    description: "Lightning-fast interceptor with superior maneuverability",
  },
  {
    id: "tiefighter",
    name: "TIE/ln Fighter",
    manufacturer: "Sienar Fleet Systems",
    baseSlots: [
      { type: "modification", filled: false },
    ],
    threatValue: 22,
    cost: 33000,
    description: "Imperial standard fighter, cheap and deadly in numbers",
  },
  {
    id: "tieinterceptor",
    name: "TIE Interceptor",
    manufacturer: "Sienar Fleet Systems",
    baseSlots: [
      { type: "modification", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 32,
    cost: 65000,
    description: "Advanced TIE variant with enhanced firepower and maneuverability",
  },
  {
    id: "tiebomber",
    name: "TIE/sa Bomber",
    manufacturer: "Sienar Fleet Systems",
    baseSlots: [
      { type: "torpedo", filled: false },
      { type: "missile", filled: false },
      { type: "missile", filled: false },
      { type: "payload", filled: false },
      { type: "payload", filled: false },
      { type: "gunner", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 29,
    cost: 60000,
    description: "Heavy ordnance platform for bombing runs",
  },
  {
    id: "bwing",
    name: "A/SF-01 B-wing",
    manufacturer: "Slayn & Korpil",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "torpedo", filled: false },
      { type: "sensor", filled: false },
      { type: "cannon", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 40,
    cost: 83000,
    description: "Heavily armed and shielded assault fighter",
  },
  {
    id: "z95",
    name: "Z-95 Headhunter",
    manufacturer: "Incom/Subpro",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "modification", filled: false },
      { type: "illicit", filled: false },
    ],
    threatValue: 22,
    cost: 22000,
    description: "Sturdy frame. Popular across the galaxy.",
  },
  {
    id: "modifiedtie",
    name: "Modified TIE/ln",
    manufacturer: "Sienar Fleet Systems",
    baseSlots: [
      { type: "modification", filled: false },
    ],
    threatValue: 20,
    cost: 22000,
    description: "TIE modified for the Mining Guild",
  },
  {
    id: "m3a",
    name: "M3-A Scyk Interceptor",
    manufacturer: "MandalMotors",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "missile", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 25,
    cost: 25000, 
    description: "Fast interceptor",
  },
  {
    id: "escapecraft",
    name: "Escape Craft",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 12,
    cost: 28000,
    description: "Long range escape craft with hyperdrive",
  },
  {
    id: "hwk290",
    name: "HWK-290",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "modification", filled: false },
      { type: "modification", filled: false },
      { type: "illicit", filled: false },
      { type: "payload", filled: false },
    ],
    threatValue: 30,
    cost: 30000,
    description: "Light freighter favored by spice runners",
  },
  {
    id: "quadjumper",
    name: "Quadrijet Space Tug",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "modification", filled: false },
      { type: "tech", filled: false },
      { type: "illicit", filled: false },
      { type: "payload", filled: false },
    ],
    threatValue: 30,
    cost: 30000,
    description: "Sturdy shipping tugboat with built in tractor array",
  },
  {
    id: "rogue",
    name: "Rogue-class Fighter",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "modification", filled: false },
      { type: "cannon", filled: false },
      { type: "illicit", filled: false },
      { type: "cannon", filled: false },
    ],
    threatValue: 35,
    cost: 37000,
    description: "Long range fighter",
  },
  {
    id: "khiraxz",
    name: "Khiraxz Fighter",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "modification", filled: false },
      { type: "modification", filled: false },
      { type: "illicit", filled: false },
      { type: "illicit", filled: false },
      { type: "missile", filled: false },
    ],
    threatValue: 41,
    cost: 40000,
    description: "Well balanced fighter",
  },
  {
    id: "fang",
    name: "Fang Fighter",
    manufacturer: "MandalMotors",
    baseSlots: [
      { type: "modification", filled: false },
      { type: "torpedo", filled: false },
    ],
    threatValue: 41,
    cost: 41000,
    description: "Maneuverable fighter favored by Mandalorian mercenaries",
  },
  {
    id: "g1a",
    name: "G-1A Starfighter",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "sensor", filled: false },
      { type: "modification", filled: false },
      { type: "illicit", filled: false },
      { type: "crew", filled: false },
      { type: "crew", filled: false },
    ],
    threatValue: 41,
    cost: 41000,
    description: "Long range heavy fighter favored by some bounty hunters",
  },
  {
    id: "jumpmaster",
    name: "JumpMaster 5000",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "modification", filled: false },
      { type: "torpedo", filled: false },
      { type: "illicit", filled: false },
      { type: "gunner", filled: false },
      { type: "crew", filled: false },
    ],
    threatValue: 41,
    cost: 42000,
    description: "Long range scout craft",
  },
  {
    id: "kimogila",
    name: "M12-L Kimogila",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "modification", filled: false },
      { type: "torpedo", filled: false },
      { type: "illicit", filled: false },
      { type: "astromech", filled: false },
      { type: "missile", filled: false },
    ],
    threatValue: 41,
    cost: 44000,
    description: "Heavy fighter favored by the Hutt Cartel",
  },
  {
    id: "scuurg",
    name: "Scuurg H-6",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "modification", filled: false },
      { type: "turret", filled: false },
      { type: "crew", filled: false },
      { type: "gunner", filled: false },
      { type: "payload", filled: false },
      { type: "payload", filled: false },
    ],
    threatValue: 45,
    cost: 45000,
    description: "Bomber favored by pirates and mercenaries",
  },
  {
    id: "st70",
    name: "ST-70 Assault Ship",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "crew", filled: false },
      { type: "illicit", filled: false },
      { type: "illicit", filled: false },
      { type: "gunner", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 47,
    cost: 47000,
    description: "Rugged, reliable, and well armed.",
  },
  {
    id: "starviper",
    name: "Starviper",
    manufacturer: "MandalMotors",
    baseSlots: [
      { type: "tech", filled: false },
      { type: "torpedo", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 55,
    cost: 55000,
    description: "High tech fighter that is expensive to produce.",
  },
  {
    id: "skipray",
    name: "GAT-12h Skipray Blastboat",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "missile", filled: false },
      { type: "torpedo", filled: false },
      { type: "turret", filled: false },
      { type: "illicit", filled: false },
      { type: "gunner", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 56,
    cost: 56000,
    description: "A well rounded assault craft favored by patrols and pirates",
  },
  {
    id: "lancer",
    name: "Lancer Pursuit Craft",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "illicit", filled: false },
      { type: "illicit", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 56,
    cost: 56000,
    description: "Powerful pursuit vessel favored by bounty hunters",
  },
  {
    id: "yv666",
    name: "YV-666 Light Freighter",
    manufacturer: "Unknown",
    baseSlots: [
      { type: "cannon", filled: false },
      { type: "missile", filled: false },
      { type: "crew", filled: false },
      { type: "crew", filled: false },
      { type: "illicit", filled: false },
      { type: "gunner", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 51,
    cost: 60000,
    description: "Easily modifiable light freighter",
  },
  {
    id: "gauntlet",
    name: "Gauntlet Fighter",
    manufacturer: "MandalMotors",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "illicit", filled: false },
      { type: "gunner", filled: false },
      { type: "payload", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 54,
    cost: 62000,
    description: "Assault and boarding craft favored by Mandalorian mercenaries",
  },
  {
    id: "pb950",
    name: "PB-950 Patrol Boat",
    manufacturer: "unknown",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "illicit", filled: false },
      { type: "gunner", filled: false },
      { type: "crew", filled: false },
      { type: "crew", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 65,
    cost: 63000,
    description: "Sturdy and well armed craft favored by local patrol and smugglers",
  },
  {
    id: "firespray",
    name: "Firewspray Patrol Boat",
    manufacturer: "MandalMotors",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "illicit", filled: false },
      { type: "payload", filled: false },
      { type: "crew", filled: false },
      { type: "cannon", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 62,
    cost: 65000,
    description: "Well armed and maneuverable patrol vessel",
  },
  {
    id: "yt1300",
    name: "YT-1300 Light Freighter",
    manufacturer: "CEC",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "illicit", filled: false },
      { type: "gunner", filled: false },
      { type: "crew", filled: false },
      { type: "crew", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 50,
    cost: 70000,
    description: "One of the most popular light freighter frames because of its ease of customization",
  },
  {
    id: "yt2400",
    name: "YT-2400 Light Freighter",
    manufacturer: "CEC",
    baseSlots: [
      { type: "missile", filled: false },
      { type: "illicit", filled: false },
      { type: "crew", filled: false },
      { type: "crew", filled: false },
      { type: "modification", filled: false },
    ],
    threatValue: 69,
    cost: 80000,
    description: "Armament bordering on illegal, this freighter is more like a gunship",
  },
  {
    id: "aggressor",
    name: "Aggressor Assault Fighter",
    manufacturer: "MandalMotors",
    baseSlots: [
      { type: "sensor", filled: false },
      { type: "cannon", filled: false },
      { type: "cannon", filled: false },
      { type: "payload", filled: false },
      { type: "illicit", filled: false },
      { type: "modification", filled: false },
      { type: "title", filled: false },
    ],
    threatValue: 64,
    cost: 80000,
    description: "Exceptionally powerful heavy fighter produced by MandalMotors",
  },
  {
    id: "luxuryshuttle",
    name: "Luxury Shuttle",
    manufacturer: "CEC",
    baseSlots: [
      { type: "crew", filled: false },
      { type: "crew", filled: false },
      { type: "crew", filled: false },
      { type: "modification", filled: false },
      { type: "configuration", filled: false },
    ],
    threatValue: 20,
    cost: 100000,
    description: "Luxury travel shuttle. Not built for combat",
  },
]

// Upgrades database
export const UPGRADES: Upgrade[] = [
  // Cannons
  {
    id: "laser1",
    name: "Standard Laser Cannon",
    type: "cannon",
    slotsRequired: 1,
    threatValue: 5,
    cost: 100,
    description: "Basic energy weapon",
  },
  {
    id: "laser2",
    name: "Heavy Laser Cannon",
    type: "cannon",
    slotsRequired: 1,
    threatValue: 10,
    cost: 250,
    description: "Increased damage output",
  },
  {
    id: "ion",
    name: "Ion Cannon",
    type: "cannon",
    slotsRequired: 1,
    threatValue: 8,
    cost: 200,
    description: "Disables enemy systems",
  },

  // Torpedoes
  {
    id: "proton",
    name: "Proton Torpedoes",
    type: "torpedo",
    slotsRequired: 1,
    threatValue: 20,
    cost: 500,
    description: "High-yield explosive ordnance",
  },
  {
    id: "adv_proton",
    name: "Advanced Proton Torpedoes",
    type: "torpedo",
    slotsRequired: 1,
    threatValue: 25,
    cost: 650,
    description: "Enhanced targeting and payload",
  },

  // Missiles
  {
    id: "concussion",
    name: "Concussion Missiles",
    type: "missile",
    slotsRequired: 1,
    threatValue: 18,
    cost: 450,
    description: "Area effect missiles",
  },
  {
    id: "homing",
    name: "Homing Missiles",
    type: "missile",
    slotsRequired: 1,
    threatValue: 15,
    cost: 400,
    description: "Lock-on tracking missiles",
  },

  // Turrets
  {
    id: "turbo",
    name: "Turbolaser Battery",
    type: "turret",
    slotsRequired: 1,
    threatValue: 35,
    cost: 800,
    description: "Capital ship grade weapon",
  },
  {
    id: "ion_turret",
    name: "Ion Cannon Turret",
    type: "turret",
    slotsRequired: 1,
    threatValue: 22,
    cost: 550,
    description: "360-degree ion coverage",
  },

  // Modifications
  {
    id: "shield1",
    name: "Shield Upgrade",
    type: "modification",
    slotsRequired: 1,
    threatValue: 5,
    cost: 150,
    description: "Enhanced deflector shields",
  },
  {
    id: "shield2",
    name: "Advanced Shields",
    type: "modification",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Military-grade shielding",
  },
  {
    id: "engine1",
    name: "Engine Upgrade",
    type: "modification",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Improved thrust and speed",
  },
  {
    id: "hull",
    name: "Hull Upgrade",
    type: "modification",
    slotsRequired: 1,
    threatValue: 6,
    cost: 200,
    description: "Reinforced hull plating",
  },

  // Tech
  {
    id: "sensor1",
    name: "Advanced Sensors",
    type: "tech",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Long range detection",
  },
  {
    id: "sensor2",
    name: "Tactical Scanner",
    type: "tech",
    slotsRequired: 1,
    threatValue: 18,
    cost: 550,
    description: "Full battlefield awareness",
  },
  {
    id: "system1",
    name: "Electronic Countermeasures",
    type: "tech",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Jamming equipment",
  },
  {
    id: "system2",
    name: "Cloaking Device",
    type: "tech",
    slotsRequired: 2,
    threatValue: 25,
    cost: 700,
    description: "Temporary invisibility",
  },

  // Crew
  {
    id: "crew1",
    name: "Co-pilot",
    type: "crew",
    slotsRequired: 1,
    threatValue: 5,
    cost: 200,
    description: "Additional crew member",
  },
  {
    id: "crew3",
    name: "Navigator",
    type: "crew",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Expert navigation assistance",
  },

  // Gunner
  {
    id: "crew2",
    name: "Expert Gunner",
    type: "gunner",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Dedicated weapons specialist",
  },
  {
    id: "gunner2",
    name: "Veteran Tail Gunner",
    type: "gunner",
    slotsRequired: 1,
    threatValue: 12,
    cost: 350,
    description: "Experienced rear defense",
  },

  // Astromech
  {
    id: "r2d2",
    name: "R2 Astromech",
    type: "astromech",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Repair and navigation droid",
  },
  {
    id: "r5",
    name: "R5 Astromech",
    type: "astromech",
    slotsRequired: 1,
    threatValue: 6,
    cost: 200,
    description: "Basic repair droid",
  },

  // Illicit
  {
    id: "cargo1",
    name: "Contraband Cybernetics",
    type: "illicit",
    slotsRequired: 1,
    threatValue: 5,
    cost: 200,
    description: "Black market enhancements",
  },
  {
    id: "cargo2",
    name: "Smuggling Compartment",
    type: "illicit",
    slotsRequired: 1,
    threatValue: 3,
    cost: 150,
    description: "Hidden cargo space",
  },

  // Payload
  {
    id: "payload1",
    name: "Seismic Charges",
    type: "payload",
    slotsRequired: 1,
    threatValue: 20,
    cost: 500,
    description: "Devastating area bombs",
  },
  {
    id: "payload2",
    name: "Proximity Mines",
    type: "payload",
    slotsRequired: 1,
    threatValue: 15,
    cost: 400,
    description: "Deployable mine field",
  },

  // Sensor
  {
    id: "sensor3",
    name: "Targeting Computer",
    type: "sensor",
    slotsRequired: 1,
    threatValue: 5,
    cost: 150,
    description: "Improved weapon accuracy",
  },
  {
    id: "sensor4",
    name: "Fire Control System",
    type: "sensor",
    slotsRequired: 1,
    threatValue: 12,
    cost: 350,
    description: "Advanced targeting suite",
  },

  // Configuration
  {
    id: "config1",
    name: "Stabilized S-Foils",
    type: "configuration",
    slotsRequired: 1,
    threatValue: 8,
    cost: 250,
    description: "Improved wing configuration",
  },
  {
    id: "config2",
    name: "Pivot Wing",
    type: "configuration",
    slotsRequired: 1,
    threatValue: 10,
    cost: 300,
    description: "Adaptive wing system",
  },

  // Title
  {
    id: "title1",
    name: "Red Squadron",
    type: "title",
    slotsRequired: 1,
    threatValue: 15,
    cost: 400,
    description: "Elite squadron designation",
  },
  {
    id: "title2",
    name: "Rogue Squadron",
    type: "title",
    slotsRequired: 1,
    threatValue: 20,
    cost: 500,
    description: "Legendary squadron status",
  },
]

// Abilities database
export const ABILITIES: Ability[] = [
  {
    id: "ace1",
    name: "Ace Pilot",
    xpCost: 50,
    threatValue: 10,
    description: "Improved maneuverability in combat",
    requiredLevel: 1,
    careers: ["Professional", "Gambler", "Miner"],
  },
  {
    id: "marks1",
    name: "Marksman",
    xpCost: 50,
    threatValue: 10,
    description: "Increased weapon accuracy",
    requiredLevel: 1,
    careers: ["Professional", "Demolitions", "Cyborg"],
  },
  {
    id: "tough1",
    name: "Tough",
    xpCost: 50,
    threatValue: 8,
    description: "Increased hull integrity",
    requiredLevel: 1,
    careers: ["Gearhead", "Cyborg", "Miner"],
  },
  {
    id: "leader1",
    name: "Squad Leader",
    xpCost: 100,
    threatValue: 15,
    description: "Bonus to nearby allies",
    requiredLevel: 2,
    careers: ["Organizer", "Professional"],
  },
  {
    id: "sniper",
    name: "Sniper",
    xpCost: 100,
    threatValue: 15,
    description: "Long range attack bonus",
    requiredLevel: 2,
    careers: ["Professional", "Demolitions"],
  },
  {
    id: "evasive",
    name: "Evasive Maneuvers",
    xpCost: 150,
    threatValue: 20,
    description: "Harder to hit in combat",
    requiredLevel: 3,
    careers: ["Gambler", "Slicer", "Miner"],
  },
  {
    id: "rapid",
    name: "Rapid Fire",
    xpCost: 150,
    threatValue: 20,
    description: "Fire weapons faster",
    requiredLevel: 3,
    careers: ["Gambler", "Demolitions", "Cyborg"],
  },
  {
    id: "shield_expert",
    name: "Shield Expert",
    xpCost: 200,
    threatValue: 18,
    description: "Shields recharge faster",
    requiredLevel: 4,
    careers: ["Slicer", "Gearhead", "Cyborg"],
  },
  {
    id: "veteran",
    name: "Veteran",
    xpCost: 200,
    threatValue: 25,
    description: "Bonus to all combat rolls",
    requiredLevel: 5,
    careers: ["Organizer", "Professional", "Miner"],
  },
  {
    id: "legendary",
    name: "Legendary Pilot",
    xpCost: 300,
    threatValue: 35,
    description: "Master of space combat",
    requiredLevel: 7,
    careers: ["Professional", "Gambler", "Cyborg"],
  },
]

// Ship dealers
export const SHIP_DEALERS: ShipDealer[] = [
  {
    id: "legitused",
    name: "Totally Legit Used Ship Broker",
    description: "Cash only. Sure the serial numbers might be missing, but they all work.",
    shipIds: ["tyewing", "ytie", "patchworkywing", "modifiedtie", "z95", "m3a", "escapecraft",
      "hwk290", "quadrijet", "ywing", "rogue", "khiraxz", "fang", "g1a", "jumpmaster", "kimogila", "scuurg",
      "st70", "starviper", "skipray", "lancer", "yv666", "gauntlet", "pb950", "firespray", "yt1300",
      "yt2400", "aggressor", "luxuryshuttle"],
  },
  {
    id: "military",
    name: "Fell Off a Freighter Military Surplus Ship Dealer",
    description: "Almost everything is for sale somewhere. Even top of the line military hardware.",
    shipIds: ["tiefighter", "tieinterceptor", "tiebomber", "lambdashuttle", "decimator", "xwing", "awing", "bwing",
      "uwing", "n1", "arc170"
    ],
  },
  {
    id: "junkyard",
    name: "Junkyard",
    description: "Roll the dice for a random salvage ship - you never know what you'll get!",
    shipIds: ["tyewing", "tnt", "ytie"],
  },
]

// Placeholder slot data - will be updated when user provides specific slot configurations
export const CAREER_PROGRESSIONS: CareerProgression[] = [
  {
    career: "Organizer",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["crew"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["crew"], threatValue: 6, initiative: 3 },
      { level: 4, xpRequired: 16, abilitySlots: 2, bonusUpgradeSlots: ["crew", "tech"], threatValue: 8, initiative: 3 },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["crew", "tech"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["crew", "tech", "illicit"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["crew", "tech", "illicit"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["crew", "crew", "tech", "illicit"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
  {
    career: "Professional",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 3 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["sensor"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["sensor"], threatValue: 6, initiative: 4 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["sensor", "tech"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["sensor", "tech"],
        threatValue: 10,
        initiative: 5,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["sensor", "tech", "crew"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["sensor", "tech", "crew"],
        threatValue: 14,
        initiative: 6,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["sensor", "sensor", "tech", "crew"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Gambler",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["illicit"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["illicit"], threatValue: 6, initiative: 3 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["illicit", "crew"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "crew"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "crew", "tech"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "crew", "tech"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "illicit", "crew", "tech"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Slicer",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 3 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["tech"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["tech"], threatValue: 6, initiative: 4 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["tech", "sensor"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["tech", "sensor"],
        threatValue: 10,
        initiative: 5,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["tech", "sensor", "tech"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["tech", "sensor", "tech"],
        threatValue: 14,
        initiative: 6,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["tech", "tech", "sensor", "sensor"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Gearhead",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["modification"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["modification"], threatValue: 6, initiative: 3 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 8,
        initiative: 3,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech", "modification"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "tech", "modification"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "modification", "tech", "tech"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
  {
    career: "Demolitions",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 2 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["missile"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["missile"], threatValue: 6, initiative: 3 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["missile", "torpedo"],
        threatValue: 8,
        initiative: 3,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["missile", "torpedo"],
        threatValue: 10,
        initiative: 4,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["missile", "torpedo", "payload"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["missile", "torpedo", "payload"],
        threatValue: 14,
        initiative: 5,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["missile", "torpedo", "payload", "cannon"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
  {
    career: "Cyborg",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 3 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["modification"], threatValue: 4, initiative: 3 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["modification"], threatValue: 6, initiative: 4 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 8,
        initiative: 4,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech"],
        threatValue: 10,
        initiative: 5,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["modification", "tech", "cannon"],
        threatValue: 12,
        initiative: 5,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "tech", "cannon"],
        threatValue: 14,
        initiative: 6,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["modification", "modification", "tech", "cannon"],
        threatValue: 16,
        initiative: 6,
      },
    ],
  },
  {
    career: "Miner",
    levels: [
      { level: 1, xpRequired: 1, abilitySlots: 1, bonusUpgradeSlots: [], threatValue: 2, initiative: 1 },
      { level: 2, xpRequired: 4, abilitySlots: 1, bonusUpgradeSlots: ["illicit"], threatValue: 4, initiative: 2 },
      { level: 3, xpRequired: 9, abilitySlots: 2, bonusUpgradeSlots: ["illicit"], threatValue: 6, initiative: 2 },
      {
        level: 4,
        xpRequired: 16,
        abilitySlots: 2,
        bonusUpgradeSlots: ["illicit", "modification"],
        threatValue: 8,
        initiative: 3,
      },
      {
        level: 5,
        xpRequired: 25,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "modification"],
        threatValue: 10,
        initiative: 3,
      },
      {
        level: 6,
        xpRequired: 36,
        abilitySlots: 3,
        bonusUpgradeSlots: ["illicit", "modification", "crew"],
        threatValue: 12,
        initiative: 4,
      },
      {
        level: 7,
        xpRequired: 49,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "modification", "crew"],
        threatValue: 14,
        initiative: 4,
      },
      {
        level: 8,
        xpRequired: 64,
        abilitySlots: 4,
        bonusUpgradeSlots: ["illicit", "illicit", "modification", "crew"],
        threatValue: 16,
        initiative: 5,
      },
    ],
  },
]

// Helper function to get career progression
export function getCareerProgression(career: CareerType): LevelProgression[] {
  const careerData = CAREER_PROGRESSIONS.find((cp) => cp.career === career)
  return careerData?.levels || CAREER_PROGRESSIONS[0].levels
}
